/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include <iostream>
#include "Parser.H"
#include "Printer.H"
#include "Absyn.H"
#include "TopDefAnalyser.H"
#include "Error.h"
#include "SemanticAnalyser.h"
#include "ThreeAddressCodeConverter.h"
#include "TACPrinter.h"
#include "BasicBlockConverter.h"
#include "CodeGenerator.h"

int main(int argc, char **argv) {
    FILE *input;
    if (argc > 1) {
        input = fopen(argv[1], "r");
        if (!input) {
            fprintf(stderr, "Error opening input file.\n");
            exit(1);
        }
    } else input = stdin;
    /* The default entry point is used. For other options see Parser.H */
    Program *parse_tree = pProgram(input);
    if (parse_tree) {
        auto *functionHeaders = new FunctionHeaders;
        TopDefAnalyser topDefAnalyser;
        topDefAnalyser.functionHeaders = functionHeaders;
        parse_tree->accept(&topDefAnalyser);
        if (topDefAnalyser.error.isError) {
            std::cerr<<"ERROR\n";
            std::cerr << topDefAnalyser.error.getErrorMessage();
            return 0;
        }
        SemanticAnalyser semanticAnalyser;
        auto *error = new Error;
        auto *symbolsTable = new SymbolsTable;
        semanticAnalyser.functionHeaders = functionHeaders;
        semanticAnalyser.symbolsTable = symbolsTable;
        semanticAnalyser.error = error;
        parse_tree->accept(&semanticAnalyser);
        delete symbolsTable;
        if (semanticAnalyser.error->isError) {
            std::cout << semanticAnalyser.error->getErrorMessage();
            delete error;
            return 0;
        }
        delete error;
        auto *threeAddressCodeConverter = new ThreeAddressCodeConverter;
        threeAddressCodeConverter->functionHeaders = functionHeaders;
        symbolsTable = new SymbolsTable;
        threeAddressCodeConverter->symbolsTable = symbolsTable;
        parse_tree->accept(threeAddressCodeConverter);
        TACPrinter tacPrinter = TACPrinter();
        // parse_tree->accept(&tacPrinter);

        auto *basicBlockConverter = new BasicBlockConverter;
        basicBlockConverter->controlFlowGraph = new ControlFlowGraph;
        basicBlockConverter->stringValues = threeAddressCodeConverter->stringValues;
        basicBlockConverter->basicBlock = new BasicBlock;
        basicBlockConverter->tacPrinter = new TACPrinter;
        basicBlockConverter->functionHeaders = functionHeaders;
        basicBlockConverter->symbolsTable = symbolsTable;
        parse_tree->accept(basicBlockConverter);

        CodeGenerator codeGenerator;
        codeGenerator.controlFlowGraph = basicBlockConverter->controlFlowGraph;
        codeGenerator.stringValues = basicBlockConverter->stringValues;
        codeGenerator.functionHeaders = functionHeaders;
        codeGenerator.allocator = new Allocator;
        codeGenerator.allocator->symbolsTable = symbolsTable;
        codeGenerator.generateCode();

        basicBlockConverter->controlFlowGraph->deleteCFG();
        delete codeGenerator.allocator;
        delete symbolsTable;
        delete threeAddressCodeConverter;
        delete functionHeaders;
        delete basicBlockConverter->controlFlowGraph;
        delete basicBlockConverter->tacPrinter;
        delete basicBlockConverter;
        return 0;
    }
    return 1;
}

